### ISSUE TITLE
Hash assets has a dependency on next.ft.com registry

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-build-tools#105]
i.e. it requires a route at the root of your web server that proxies to s3.

Express work-around. Maybe just add this to the README?

```
var http = require('http');

app.get('/hashed-assets/:path*', function(req, res) {
	var path = 'http://ft-next-hashed-assets-prod.s3-website-eu-west-1.amazonaws.com' + req.path;
	console.log(path);
	http.get(path, function(proxyRes) {
		proxyRes.pipe(res);
	});
});
```

**Comment by matthew-andrews** [comment]
Going to work with @richard-still-ft to switch all our assety things to http2 so these URLs will become absolute, not relative which will solve this I think :smile:.

https://h2-next.ft.com/hashed-assets/blahblahblah.css

**Comment by matthew-andrews** [comment]
no longer a problem, i believe
