### ISSUE TITLE
Overriding dummy test keys in nbt run

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-build-tools#157]
I just ran `make test` in ilyushin, which sets `export ELASTIC_SEARCH_HOST=123.sfdsf.com`

Subsequently `nbt run` does not set this key to its proper value as it is already defined.

Feature or bug?

**Comment by matthew-andrews** [comment]
feature :-)

i think it should always prefer the keys of the environment over the default ones.  would accept a PR that added logging to be more explicit about what is going on though ?

**Comment by wheresrhys** [comment]
a possible sub-bug though - I ran `export ELASTIC_SEARCH_HOST=` to clear the key... but still not overwritten by nbt. This may just be a hole in my bash knowledge; Is there a better way to clear env vars?

**Comment by matthew-andrews** [comment]
that should do it…… i'll come over

**Comment by matthew-andrews** [comment]
`unset` seems to be the way forward
