### ISSUE TITLE
Remove gtg from master builds

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-build-tools#174]
Thinking more about `/__gtg` - it's actually fairly meaningless on master at the moment as the last deploy will still be serving the app at the time of hitting `__gtg`. So - controversially - shall we not bother with __gtg on master deploys? Instead rely on sensu/pingdom to tell us post-deploy if something's gone wrong

**Comment by matthew-andrews** [comment]
this is only meaningless at the moment because we use preboot.  it's _mostly_ harmless as is and would become necessary again if/when we change from using preboot to using something else.

needs some thought before we remove this.

**Comment by wheresrhys** [comment]
I advocate adding an `if (is master) {skip gtg}` type thing. Easily removeable if and when gtg does become useful

**Comment by matthew-andrews** [comment]
slightly better idea…  if `skipEnablePreboot` NOT `true` THEN skip gtg check on deploy.

then if/when we change preboot, the check'll come back?

and we can put a comment above that `if` saying `gtg` check makes no sense when prebooting.

**Comment by wheresrhys** [comment]
:+1::+1:

On 12 August 2015 at 08:59, Matt Andrews <notifications@github.com> wrote:

> slightly better idea… if skipEnablePreboot NOT true THEN skip gtg check
> on deploy.
>
> then if/when we change preboot, the check'll come back?
>
> and we can put a comment above that if saying gtg check makes no sense
> when prebooting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-build-tools/issues/174#issuecomment-130209910>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by matthew-andrews** [comment]
@wheresrhys would you like to do this or should i?

**Comment by matthew-andrews** [comment]
thanks for your help @wheresrhys and sorry for the confusion not having this caused.
