### ISSUE TITLE
Should fail/warn if not running gtar

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-build-tools#18]
It's helpful for people to be made aware of the problems. Would have saved @spriggsha 30 mins this morning had he realised he'd switched machines without gnutar on.

**Comment by matthew-andrews** [comment]
it should support bsd-tar fine (it used to) but there's a bug I need to fix…  was the OS harry struggling with OSX Yosemite?

**Comment by matthew-andrews** [comment]
this is a bug in haikro not nbt.
