### ISSUE TITLE
If NBT shouldn't be installed globally, how to make it work in a Makefile?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-build-tools#326]
e.g. [next-stream-page's Makefile](https://github.com/Financial-Times/next-stream-page/blob/master/Makefile) includes `nbt` commands (plus `obt` and `mocha`). I'd rather not install these globally, and the NBT readme specifically warns against this anyway.

Is there a Next-approved way of making it so my PATH includes the local `./node_modules/.bin` whenever I run `make`?

**Comment by matthew-andrews** [comment]
http://financial-times.github.io/next/docs/developer-guide/troubleshooting/

Can’t find nodemon, mocha, etc. Your path might be missing node_modules/.bin. Edit your .bashrc or .bash_profile file and ensure your path has the following paths added to it:-
export PATH="node_modules/.bin:$PATH" Then run source ~/.bash_profile to add it to your current terminal session
