### ISSUE TITLE
Custom way of configuring ESLint is incompatible with third party tools

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-build-tools#327]
cc @AlbertoElias

### problem

Tools that interact with ESLint, such as [as-you-type lint highlighters](https://atom.io/packages/linter), don't work in a Next app or Origami component without some hacking.

### why

nbt and obt keep their ESLint configs in custom locations. The `nbt/obt verify` tasks know about this, but the `eslint` command doesn't.

### proposed fix

Embrace ESLint's standard approaches for explicit [shared configs](http://eslint.org/docs/developer-guide/shareable-configs) and [inheritance](http://eslint.org/docs/user-guide/configuring#extending-configuration-files):

- Publish our configs on npm. For example, we could have three modules:
  - `eslint-config-ft` – base config (for rules we want to enforce universally, like `eqeqeq: 2` – i.e. anything that [this](https://github.com/Financial-Times/origami-build-tools/blob/master/config/.eslintrc) and [this](https://github.com/Financial-Times/next-build-tools/blob/master/config/eslint.json) have in common)
  - `eslint-config-ft-browser` – extends the base config with `browser: true` and any browser-specific rules
  - `eslint-config-ft-node` – extends the base config with `"node": true` and any node-specific rules
- Next apps would have in their package.json: `"eslintConfig": {"extends": "ft-node"}`
- Origami components (and `n-*` components?) would have in their package.json: `"eslintConfig": {"extends": "ft-browser"}`
- Update nbt and obt to stop them setting a custom config path when running eslint (just let eslint figure it out)

I think the easiest way to do this would be with a major version bump in both origami-build-tools and next-build-tools, so it's a clean break from the old way.

**Comment by matthew-andrews** [comment]
Did you mean to raise this issue here?  Seems like an OBT issue.

**Comment by callumlocke** [comment]
I'd say it's both, as it would need to be fixed with a corresponding major version bump in both obt and nbt. But I can repost it over there if you want?

**Comment by AlbertoElias** [comment]
Please come to the origami meeting on Thursday, I'll wait from releasing obt v5 until then. Though adding something to every module is very costly, and having obt, the benefits of running eslint in the cli are quite limited, so I'm rather hesitant about it

cc @triblondon @alicebartlett

**Comment by matthew-andrews** [comment]
> something to every module is very costly

I agree with Alberto on this, and it makes it easier for Origami to switch between linters… e.g. going from JSHint to ESLint was more straight forward than it would have been had every module had to have `jshint` properties in their `package.json` files that would need updating…… …… …… 

The way some devs on Next workaround this sort of thing (e.g. also with `.editorconfig` files) is they have some little scripts to creating these sorts of files on their local filesystems (and they're then `.gitignore`d) so that their editors can pick them up but they don't go the codebase.

**Comment by callumlocke** [comment]
> adding something to every module is very costly

the new stuff in package.json wouldn't need to be done until a given module is having its obt/nbt dependency upgraded, at which point it's being updated anyway

> the benefits of running eslint in the cli are quite limited

I suppose it's subjective, but personally I really value having linting in my editor, it helps me no end

**Comment by AlbertoElias** [comment]
yes, but keep in mind that the time it takes you to copy the linting config file to your home directory, compared to updating every single module (currently Origami modules don't have obt as a dependency) is quite large. A lot of developers I know have done that, we even have an explanation of how to set it up in the documentation: http://origami.ft.com/docs/developer-guide/background-linters/

**Comment by callumlocke** [comment]
Ok I'll just use global configs for next then.
