### ISSUE TITLE
make tidy behaviour when build fails

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-build-tools#60]
I think it should probably not run if nightwatch fails (so that you can visit that app to debug), and if nightwatch succeeds should tidy up its own app and any apps with hashes of parent commits.

That's the ideal behaviour in my view, but it probably adds a lot of complexity for not that much benefit.

**Comment by matthew-andrews** [comment]
i'd be happy to get rid of tidy for all cases if we had something that reliably go around and delete the apps after a reasonable lenght of time (1 day).  i want that to be scrooge bot (ask @captain-sysadmin) and I want that to be built by the infrastructure/internal tools team, not us.
