### ISSUE TITLE
Make install task for next build tools

### ISSUE THREAD

**Issue by tom-parker** [Financial-Times/next-build-tools#76]
This will remove the dependency on the install task of origami-build-tools as requested by @matthew-andrews

**Comment by matthew-andrews** [comment]
thanks!

**Comment by matthew-andrews** [comment]
hmm…… this is annoying and needs more thought.  this would mean that our install mechanism would depend on itself already being installed………

**Comment by matthew-andrews** [comment]
i'm actually cool with every app hardcoding `npm install && origami-build-tools install` considering the circularness of this.
