### ISSUE TITLE
Prevent deploy of old commits on master

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-build-tools#89]
In travis it's easy to accidentally trigger a build on a non-HEAD commit of master which will trigger a deploy. We should try to prevent this and provide an informative error e.g.

> You're building an old commit on the master branch. You probably want to
  - Rebuild and deploy the latest commit, for which the build history list should be your first port of call
  - Rollback to an earlier version, for which heroku should be used
  - Do something else with this build, in which case create a branch from this commit

**Comment by matthew-andrews** [comment]
other people must have this problem……  do you know of any solutions out there?

**Comment by wheresrhys** [comment]
http://docs.travis-ci.com/api/#branches looked like the route to take, but after playing around a bit it looks like the travis ci is in general very fond of returning its own internal ids, but hardly any endpoint ever exposes branch names or commit hashes, so it's not very usable for this purpose. 

Installing the travis gem as a dependency of nbt would do the trick as the cli does return useful branch info http://docs.travis-ci.com/api/?shell#branches. But I don't think we should add an extra dependency.

I think the thing to do is to ask travis to put human (& git!!) readable info in their api responses. I'm immensely surprised they don't already do so.

**Comment by matthew-andrews** [comment]
I think `nbt rebuild` cover this reasonably OK
